const components = [
  { id: 1, emote: '📣', title: 'Alerts', count: 0 + ' components' },
  { id: 2, emote: '🏆', title: 'Badges', count: 0 + ' components' },
  { id: 3, emote: '🍞', title: 'Breadcrumbs', count: 0 + ' components' },
  { id: 4, emote: '🎹', title: 'Buttons', count: 0 + ' components' },
  { id: 5, emote: '🃏', title: 'Cards', count: 0 + ' components' },
  { id: 6, emote: '🥏', title: 'Dropdowns', count: 0 + ' components' },
  { id: 7, emote: '⚠️', title: 'Error Pages', count: 0 + ' components' },
  { id: 8, emote: '📄', title: 'Forms', count: 0 + ' components' },
  { id: 9, emote: '🦰', title: 'Header', count: 0 + ' components' },
  { id: 10, emote: '⌨️', title: 'Inputs', count: 0 + ' components' },
  { id: 11, emote: '🗺️', title: 'Navigations', count: 0 + ' components' },
  { id: 12, emote: '🚧', title: 'Progress', count: 0 + ' components' },
  { id: 13, emote: '📻', title: 'Radio Groups', count: 0 + ' components' },
  { id: 14, emote: '🗃️', title: 'Selects', count: 0 + ' components' },
  { id: 15, emote: '🎫', title: 'Side Menus', count: 0 + ' components' },
  { id: 16, emote: '📊', title: 'Stats', count: 0 + ' components' },
  { id: 17, emote: '📅', title: 'Steps', count: 0 + ' components' },
  { id: 18, emote: '🍽️', title: 'Tables', count: 0 + ' components' },
  { id: 19, emote: '🦿', title: 'Toggles', count: 0 + ' components' },
  { id: 20, emote: '🎴', title: 'Vertical Menus', count: 0 + ' components' },
];
