const componentsList = [
  { id: 1, emote: '📣', title: 'Alerts' },
  { id: 2, emote: '🏆', title: 'Badges' },
  { id: 3, emote: '🍞', title: 'Breadcrumbs' },
  { id: 4, emote: '🎹', title: 'Buttons' },
  { id: 5, emote: '🃏', title: 'Cards' },
  { id: 6, emote: '🥏', title: 'Dropdowns' },
  { id: 7, emote: '⚠️', title: 'Error Pages' },
  { id: 8, emote: '📄', title: 'Forms' },
  { id: 9, emote: '🦰', title: 'Header' },
  { id: 10, emote: '⌨️', title: 'Inputs' },
  { id: 11, emote: '🗺️', title: 'Navigations' },
  { id: 12, emote: '🚧', title: 'Progress' },
  { id: 13, emote: '📻', title: 'Radio Groups' },
  { id: 14, emote: '🗃️', title: 'Selects' },
  { id: 15, emote: '🎫', title: 'Side Menus' },
  { id: 16, emote: '📊', title: 'Stats' },
  { id: 17, emote: '📅', title: 'Steps' },
  { id: 18, emote: '🍽️', title: 'Tables' },
  { id: 19, emote: '🦿', title: 'Toggles' },
  { id: 20, emote: '🎴', title: 'Vertical Menus' },
];
